from pathlib import Path

from ice.paper import Paper


def test_pdf():
    script_path = Path(__file__).parent
    paper = Paper.load(script_path / "../papers/abebe-2018.pdf")
    sentences = list(paper.sentences())
    assert (
        sentences[0]
        == "We show that an easy-to-scale intervention that helps young job-seekers to signal their ability to employers can generate large improvements in labor market outcomes."
    )
    assert sentences[-1] == "A.22 A.25"


def test_txt():
    script_path = Path(__file__).parent
    paper = Paper.load(script_path / "../papers/abebe-2018-small.txt")
    sentences = list(paper.sentences())
    assert (
        sentences[0]
        == "We show that an easy-to-scale intervention that helps young job-seekers to signal their ability to employers can generate large improvements in labor market outcomes."
    )
    assert (
        sentences[-1]
        == "Overall, these results illustrate the large equity gains that can be generated by helping young workers to access the labour market through improved signalling."
    )
